controller:
  replicaCount: 2  # Số lượng replica của controller
  metrics:
    enabled: true  # Bật tính năng metrics
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"  # Annotation cho service LoadBalancer (AWS)
  config:
    use-forwarded-headers: "true"  # Sử dụng forwarded headers
    compute-full-forwarded-for: "true"  # Tính toán full forwarded for header
    use-proxy-protocol: "true"  # Sử dụng proxy protocol
    proxy-body-size: "50m"  # Giới hạn kích thước body của proxy

defaultBackend:
  enabled: true
  image:
    repository: k8s.gcr.io/defaultbackend
    tag: ""
    pullPolicy: IfNotPresent

rbac:
  create: true  # Tạo RBAC resources nếu không có

image:
  repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
  tag: ""
  pullPolicy: IfNotPresent

admissionWebhooks:
  enabled: true

publishService:
  enabled: false

updateStrategy:
  type: RollingUpdate

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingressClass:
  enabled: true
  name: nginx  # Tên của IngressClass

tcp:
  "3000": "default/example-service:3000"  # Cấu hình TCP services

udp:
  "53": "kube-system/kube-dns:53"  # Cấu hình UDP services

extraArgs:
  default-ssl-certificate: "kube-system/default-cert"  # Các argument bổ sung

extraVolumes:  # Các volumes bổ sung
  - name: extra-config
    configMap: nginx-configmap
  - name: extra-secrets
    secret: nginx-secrets

extraVolumeMounts:  # Các mount bổ sung
  - name: extra-config
    mountPath: /etc/nginx/extra-config
    readOnly: true
  - name: extra-secrets
    mountPath: /etc/nginx/extra-secrets
    readOnly: true

serviceAccount:
  create: true
  name: nginx-ingress-serviceaccount

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  # Annotation cho Ingress
  hosts:
    - host: example.com
      paths:
        - path: /app
          pathType: Prefix
          backend:
            service:
              name: example-service
              port:
                number: 80

## SSL Configuration
## Uncomment the following lines to enable SSL
##
# tls:
#   - secretName: example-tls-secret
#     hosts:
#       - example.com

## Additional Ingress Controller Configurations
##
# controller:
#   config:
#     use-proxy-protocol: "true"
#     use-forwarded-headers: "true"
#     compute-full-forwarded-for: "true"
#     enable-underscores-in-headers: "true"

## Metrics Configuration
##
# controller:
#   metrics:
#     enabled: true
#     service:
#       annotations:
#         prometheus.io/scrape: "true"
#         prometheus.io/port: "10254"

## Service Configuration
##
# controller:
#   service:
#     annotations:
#       service.beta.kubernetes.io/aws-load-balancer-internal: "true"

## Pod Annotations and Labels
##
# controller:
#   podAnnotations:
#     key: value
#   podLabels:
#     key: value

## Configuration for Default Backend
##
# defaultBackend:
#   enabled: true
#   image:
#     repository: k8s.gcr.io/defaultbackend
#     tag: "1.5"
#     pullPolicy: IfNotPresent

## RBAC Configuration
##
# rbac:
#   create: true

## Image Configuration
##
# image:
#   repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
#   tag: "1.0.0"
#   pullPolicy: IfNotPresent

## Configuration for Admission Webhooks
##
# admissionWebhooks:
#   enabled: true

## Configuration for Publish Service
##
# publishService:
#   enabled: false

## Update Strategy Configuration
##
# updateStrategy:
#   type: RollingUpdate

## Resource Requests and Limits
##
# resources:
#   limits:
#     cpu: 100m
#     memory: 128Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi

## Ingress Class Configuration
##
# ingressClass:
#   enabled: true
#   name: nginx

## TCP and UDP Services Configuration
##
# tcp:
#   "3000": "default/example-service:3000"
# udp:
#   "53": "kube-system/kube-dns:53"

## Additional Arguments
##
# extraArgs:
#   default-ssl-certificate: "kube-system/default-cert"

## Additional Volumes and Volume Mounts
##
# extraVolumes:
#   - name: extra-config
#     configMap: nginx-configmap
#   - name: extra-secrets
#     secret: nginx-secrets
# extraVolumeMounts:
#   - name: extra-config
#     mountPath: /etc/nginx/extra-config
#     readOnly: true
#   - name: extra-secrets
#     mountPath: /etc/nginx/extra-secrets
#     readOnly: true

## Service Account Configuration
##
# serviceAccount:
#   create: true
#   name: nginx-ingress-serviceaccount
